version: 2
updates:
# 1. Node.js dependencies
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  reviewers:
  - "user-cube"
  labels:
  - "dependencies"
  commit-message:
    prefix: "dependabot"

# 2. GitHub Actions (CI/CD workflows)
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "ci"
  commit-message:
    prefix: "dependabot"
